### ISSUE TITLE
missing credit

### ISSUE THREAD

**Issue by evilmog** [NotSoSecure/password_cracking_rules#1]
generated2.rule is missing credit:

From the oclHashcat v1.20 changelog:

Type: Feature
File: Rules
Desc: Added generated2.rule, each one cracked a real hash, sorted by occourance. use head -XXXX to make a top XXXX
Cred: EvilMog

I spent 6 months generating that rule

**Comment by anantshri** [comment]
@evilmog Thanks for the head's up. Credit's added. Thanks for all the hardwork you have done.
