### ISSUE TITLE
Ruleset is skipped

### ISSUE THREAD

**Issue by whoot** [NotSoSecure/password_cracking_rules#3]
When using the OneRuleToRuleThemaAll.rules in Hashcat (3.6.0 on Windows), hashcat shows the following warning:

```
Skipping invalid or unsupported rule in file rules\OneRuleToRuleThemAll.rule on line 8210: ^o^─à^─é^o^t
Skipping invalid or unsupported rule in file rules\OneRuleToRuleThemAll.rule on line 42459: ^a^─à^─é^e^s^a^r^t^n^o^c
```

**Comment by stealthsploit** [comment]
Can you provide more information about the type of hash you were cracking and the hashcat command you used please?

**Comment by whoot** [comment]
Sure. I tried to crack NTLM Hashes with the following command:

> hashcat64.exe -m 1000 -r rules\OneRuleToRuleThemAll.rule hashes.txt wordlists\rockyou.txt --force

**Comment by stealthsploit** [comment]
Thanks for the update, yes that's the issue, those characters (originally from the KoreLogic ruleset) are non-ascii and UTF-8 / ISO 8859-2 requires tweaking. Wide characters aren't supported in hashcat. Glad you sorted it.

**Comment by yuuwe-n** [comment]
@whoot how were you able to save the rules with the encoding?

**Comment by whoot** [comment]
@PunkmeisterDuy Opened it with Sublime Text and selected "Save with Encoding ..." ;)
But you may also use iconv under Linux. Command should be something like this: ```iconv -f utf-8 -t ISO_8859-2 OneRuleToRuleThemAll.rules```

**Comment by yuuwe-n** [comment]
@whoot thank you for replying. I used iconv for it before and getting illegal input sequence at 6058, but I think that is just for one line and doesn't matter overall. However, when using hashcat I am still getting invalid or unsupported rule in file. 

Thank you so much for your time.

**Comment by yuuwe-n** [comment]
@whoot nevermind I just installed sublime text instead and saved it with the encoding, thank you for the help
