### ISSUE TITLE
wordlist used in testing?

### ISSUE THREAD

**Issue by roycewilliams** [NotSoSecure/password_cracking_rules#5]
Could you note (at least broadly) in the README what _wordlists_ were used during this testing?

(Rules don't exist in isolation - they are strongly dependent on what the input wordlists were.)

Thanks!

**Comment by anantnss** [comment]
Hi Royce,

https://github.com/NotSoSecure/password_cracking_rules#credit-where-credit-is-due <- the rules were created based on other rules as credited here.

-Anant

**Comment by roycewilliams** [comment]
My question wasn't where the *rules* came from. :) My question is about what *wordlists* were used to *test* the rules, to come up with the "top 25% performing" test results as noted here:

https://github.com/NotSoSecure/password_cracking_rules/blob/master/OneRuleToRuleThemAll.rule#L3 says:

This 25% performance metric would have to be tested using *specific wordlists* as inputs.

In other words, to test performance of these rules, the command would be:
```
hashcat -a 0 [target.hash] -r [rule] [wordlist]
```
You've disclosed what rules were used to create `[rule]`. What wordlists were used to created `[wordlist]` ?

**Comment by anantnss** [comment]
Ah my bad

Ref: https://www.notsosecure.com/one-rule-to-rule-them-all/

We used rockyou dictionary and hopefully the blog will give you more insights.
